# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI Pipe

on:
  pull_request:
    branches: [ "master" ]
    paths:
      - 'mindnlp/**'
      - 'tests/ut/**'
      - '!mindnlp/dataset/**'
      - '!tests/ut/dataset/**'
      - '!docs/**'
      - '.github/workflows/**'
  push:
    branches: [ "master" ]
    paths:
      - 'mindnlp/**'
      - '!mindnlp/dataset/**'
      - '!docs/**'

permissions:
  contents: read

jobs:
  pylint-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/requirements.txt
    - name: Install MindSpore
      shell: bash
      env:
        OS: ubuntu-latest
        PYTHON: 3.7
      run: |
        python .github/install_mindspore.py
        pip install -r download.txt
    - name: Analysing the mindnlp code with pylint
      run: |
        pylint mindnlp --rcfile=.github/pylint.conf
    - name: Analysing the tests code with pylint
      run: |
        pylint tests --rcfile=.github/pylint.conf

  
